### ISSUE TITLE
Dashboard MAP (Entity and Location) isn't Work

### ISSUE THREAD

**Issue by Gambware** [stdonato/glpi-dashboard#4] opened 2017-02-08 17:07 UTC
Hi,

This problem ever happening in my GLPI, I update the Dashboard Plugin to 0.80 see if will work, but still showing the same problem. 

Do you know what can I do to solve this? 

![image](https://cloud.githubusercontent.com/assets/24397740/22748097/973738a2-edee-11e6-85ea-2e8a383a3de6.png)

Thanks !! 
Congrats for this project it's Amazing!!!

**Comment by Gambware** [comment] 2017-02-08 19:09
For more information, I'm trying to debbug, I guess that could be something related with Google Maps API 

![image](https://cloud.githubusercontent.com/assets/24397740/22752936/e24a2ed8-edff-11e6-911c-12dac6ae1827.png)

**Comment by stdonato** [comment] 2017-02-08 19:15
Hi, i know this errors. I trying to figure out the cause.
What yours O.S. ? Is your server local or hosted? 
If your server is local and not have internet access, the maps don't will work.

**Comment by Gambware** [comment] 2017-02-08 19:35
Thanks for answer!

OS. Ubuntu 14.04.1
My Server in hosted (Cloud on Microsoft Azure)
The Server has internet access

**Comment by stdonato** [comment] 2017-02-08 20:57
This problem occurs in hosted servers and i dont have one to test.
The plugin dont convert address in coordinates. The errors seems be in google geocoding  API.
The first time you use the map, all entities addresses are converted in coordinates using geocode api and recorded in database. 
I am working in client side geocoding with javascript to solve this issue.

**Comment by Gambware** [comment] 2017-02-09 15:04
I can provide a Virtual Machine on Windows Azure to you execute the tests.
Please send me an email if you want and I send to you an access to a Virtual Machine. 
paulo@gambware.com

**Comment by stdonato** [comment] 2017-02-17 01:03
Hi, download and test maps from new version: https://forge.glpi-project.org/projects/dashboard/files

**Comment by Gambware** [comment] 2017-02-17 20:03
Now it's working pretty well !! Thanks Advanced!!

**Comment by AircraftRu** [comment] 2017-02-21 06:18
It's work. But it is not transferred to Administration -> Entities -- "Dashboard Map"
When saving the key, nothing happens, it is best if the card is opened.
On Ubuntu server "Map by Location" not working map.
By default, the type of satellite maps, it is better if there is a map.
https://developers.google.com/maps/documentation/javascript/maptypes?hl=en.

Regards,
Nikolay Petrov

**Comment by stdonato** [comment] 2017-02-22 17:53
Partially  solved in 0.8.1.

**Closed by stdonato** 2017-02-22 17:53 UTC
